site_name: Hands-on DevSecOps
# site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/

nav:
  - Home: index.md
  - Kubernetes: 
    - ArgoCD deployemnt patterns: k8s/argocd-deployment-patterns.md
  - Observability: 
    - Getting started with Loki & Grafana: observability/getting-started-with-loki-grafana.md
    - Monitoring k8s audit logs with Grafana: observability/monitoring-k8s-audit-logs-with-grafana.md
  - Other Topics: 
    - Mkdocs Examples: other/examples.md
  # - Supply Chain Security: devsecops-tools.md
  # - DevSecOps Pipeline: devsecops-pipeline.md
  # - DevSecOps Implementation: devsecops-implementation.md
  # - DevSecOps Challenges: devsecops-challenges.md
  # - DevSecOps Conclusion: devsecops-conclusion.md
  # - DevSecOps References: devsecops-references.md
  # - DevSecOps About: devsecops-about.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

# plugins:
#   - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aminrj
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aminerj
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/araji/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://aminrj.com"  target="_blank" rel="noopener">Amine Raji</a>
